### ISSUE TITLE
support for v2 and nuxt

### ISSUE THREAD

**Issue by 1shaked** [iann838/vue-scriptx#1]
Can you please provide info on nuxt.js and I think that vue-script2  is not maintained
Also be happy if I could fork you and help you develop this

**Comment by ianhco** [comment]
@1shaked Sure, you can fork it, contribution appreatiated.

That said, I personally have not worked with nuxt, so I can't really provide anything for it. Vue2 hooks it's not at all compatible with Vue3 without a big hack under the way that might impact performance, so I would like to reject that idea, but I do want to see support for nuxt.
